Repository penguinsAtEgloo/E-Gloo, pull requests merged in 2021-07, with the labels that each got.

#15 feature/BE/login
  back-end-api/src/main/java/com/project/egloo/EglooApplication.java
  back-end-api/src/main/java/com/project/egloo/MemberService.java
  back-end-api/src/main/java/com/project/egloo/common/StatusCode.java
  back-end-api/src/main/java/com/project/egloo/controller/MemberController.java
  back-end-api/src/main/java/com/project/egloo/domain/Member.java
  back-end-api/src/main/java/com/project/egloo/repository/MemberRespository.java
Labels: backend, enhancement

#17 Chore/frontend config
  front-end/.babelrc
  front-end/.editorconfig
  front-end/.gitignore
  front-end/README.md
  front-end/assets/css/common.css
  front-end/assets/logo.svg
  front-end/components/Navbar.vue
  front-end/components/Notification.vue
  front-end/jest.config.js
  front-end/layouts/default.vue
  front-end/layouts/profile.vue
  front-end/nuxt.config.js
  front-end/package.json
  front-end/pages/index.vue
  front-end/pages/profile.vue
  front-end/pages/register.vue
  front-end/static/favicon.ico
  front-end/store/README.md
  front-end/store/index.js
  front-end/test/NuxtLogo.spec.js
Labels: configuration, frontend

#20 feature/FE/login
  front-end/components/Navbar.vue
  front-end/layouts/profile.vue
  front-end/middleware/authenticated.js
  front-end/nuxt.config.js
  front-end/pages/index.vue
  front-end/pages/login.vue
  front-end/pages/profile.vue
  front-end/store/index.js
Labels: configuration, frontend

#22 (#18) 회원가입 기능개발
  back-end-api/src/main/java/com/project/egloo/MemberService.java
  back-end-api/src/main/java/com/project/egloo/controller/MemberController.java
  back-end-api/src/main/java/com/project/egloo/domain/Member.java
  back-end-api/src/main/java/com/project/egloo/dto/response/SignUpResponse.java
  back-end-api/src/main/java/com/project/egloo/repository/MemberRespository.java
  back-end-api/src/main/java/com/project/egloo/service/MemberService.java
Labels: backend, enhancement

#33 (#24)backend package configuration
  back-end-api/logs/spring.log
  back-end-api/src/main/java/com/project/egloo/dto/request/SignUpRequest.java
  back-end-api/src/main/java/com/project/egloo/member/controller/MemberController.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Gender.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Member.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Social.java
  back-end-api/src/main/java/com/project/egloo/member/dto/request/SignUpRequest.java
  back-end-api/src/main/java/com/project/egloo/member/dto/response/SignUpResponse.java
  back-end-api/src/main/java/com/project/egloo/member/repository/MemberRespository.java
  back-end-api/src/main/java/com/project/egloo/member/service/MemberService.java
Labels: backend, configuration

#40 (#39) 프로젝트 전체 .gitignore 추가, .vscode 폴더 삭제
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
Labels: configuration

#45 (#44) Bug Fix
  front-end/components/GeneralInput.vue
  front-end/components/RegisterModal.vue
  front-end/components/SwitchTabInput.vue
  front-end/package.json
  front-end/pages/index.vue
  front-end/pages/login.vue
  front-end/pages/profile.vue
  front-end/store/index.js
Labels: bug

#47 (#41) CORS 설정
  back-end-api/src/main/java/com/project/egloo/common/WebConfig.java
Labels: backend, bug, configuration

#50 (#26) 요리가능레시피탭 UI추가
  back-end-api/src/main/java/com/project/egloo/member/controller/MemberController.java
  front-end/assets/css/common.css
  front-end/assets/images/bookmark.svg
  front-end/assets/images/clock.svg
  front-end/assets/images/difficulty.svg
  front-end/assets/images/image1.jpg
  front-end/assets/images/no-image.svg
  front-end/assets/logo.svg
  front-end/components/Recipe.vue
  front-end/components/RecipeGallery.vue
  front-end/components/RegisterModal.vue
  front-end/components/TabItem.vue
  front-end/layouts/default.vue
  front-end/layouts/navbar.vue
  front-end/layouts/tab.vue
  front-end/nuxt.config.js
  front-end/package.json
  front-end/pages/index.vue
  front-end/pages/recipes.vue
  front-end/static/favicon.ico
  front-end/store/actions.js
  front-end/store/getters.js
  front-end/store/index.js
  front-end/store/mutations.js
Labels: enhancement, frontend, 레시피

#55 (#54) 레시피 엔티티 추가
  back-end-api/src/main/java/com/project/egloo/member/domain/Category.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Difficulty.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Recipe.java
  back-end-api/src/main/java/com/project/egloo/member/domain/RecipeProcess.java
  back-end-api/src/main/java/com/project/egloo/member/repository/RecipeRepository.java
  back-end-api/src/main/java/com/project/egloo/member/service/RecipeService.java
Labels: backend, enhancement, 레시피

#58 (#57) 재료, 재료-레시피 매핑 테이블 추가
  back-end-api/src/main/java/com/project/egloo/common/StatusCode.java
  back-end-api/src/main/java/com/project/egloo/member/controller/RecipeController.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Ingredient.java
  back-end-api/src/main/java/com/project/egloo/member/domain/IngredientRecipeIdClass.java
  back-end-api/src/main/java/com/project/egloo/member/domain/IngredientRecipeMapping.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Unit.java
Labels: backend, 레시피, 재료

#59 (#56) 재료 선택 페이지 UI 및 Grid 컴포넌트
  front-end/assets/images/no-image.svg
  front-end/components/Grid.vue
  front-end/components/Ingredient.vue
  front-end/components/Recipe.vue
  front-end/components/RecipeGallery.vue
  front-end/components/TabItem.vue
  front-end/layouts/tab.vue
  front-end/pages/index.vue
  front-end/pages/ingredients.vue
  front-end/pages/recipes.vue
  front-end/store/index.js
  front-end/store/mutations.js
Labels: enhancement, frontend, 재료

#60 (#31) 레시피 검색 기능
  back-end-api/src/main/java/com/project/egloo/member/controller/RecipeController.java
  back-end-api/src/main/java/com/project/egloo/member/repository/IngredientRecipeMappingRepository.java
  back-end-api/src/main/java/com/project/egloo/member/service/RecipeService.java
Labels: backend, enhancement, 레시피, 재료

#64 (#63) Transition css added and minor css fix
  front-end/assets/css/transition.css
  front-end/assets/images/multiply.svg
  front-end/components/GeneralInput.vue
  front-end/components/Modal.vue
  front-end/components/RegisterModal.vue
  front-end/components/SwitchTabInput.vue
  front-end/nuxt.config.js
  front-end/package.json
  front-end/pages/index.vue
  front-end/pages/login.vue
Labels: frontend

#67 (#66) Jest 환경설정
  front-end/components/Ingredient.vue
  front-end/jest.config.js
  front-end/package.json
  front-end/test/Components.spec.js
  front-end/test/NuxtLogo.spec.js
  front-end/test/jest.setup.js
Labels: frontend
