Repository penguinsAtEgloo/E-Gloo, pull requests merged in 2021-08, with the labels that each got.

#69 (#51)spring security configuration
  back-end-api/build.gradle
  back-end-api/src/main/java/com/project/egloo/config/security/AppProperties.java
  back-end-api/src/main/java/com/project/egloo/config/security/SecurityConfig.java
  back-end-api/src/main/java/com/project/egloo/config/security/UserPrincipal.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Member.java
  back-end-api/src/main/java/com/project/egloo/member/domain/MemberRole.java
  back-end-api/src/main/java/com/project/egloo/member/repository/MemberRepository.java
  back-end-api/src/main/java/com/project/egloo/member/repository/MemberRespository.java
  back-end-api/src/main/java/com/project/egloo/member/service/CustomMemberDetailsService.java
  back-end-api/src/main/java/com/project/egloo/member/service/MemberService.java
Labels: backend, configuration

#70 (#35) feature global exception
  back-end-api/src/main/java/com/project/egloo/common/exceptions/AuthException.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/BusinessException.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/EntityNotFoundException.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/ErrorCode.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/ErrorResponse.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/GlobalExceptionHandler.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/InvalidValueException.java
Labels: backend, enhancement

#73 (#72) configuration (recipe, member, ingredient) package
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/Ingredient.java
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/IngredientRecipeIdClass.java
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/IngredientRecipeMapping.java
  back-end-api/src/main/java/com/project/egloo/ingredient/repository/IngredientRecipeMappingRepository.java
  back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Category.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Difficulty.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Recipe.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/RecipeProcess.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Unit.java
  back-end-api/src/main/java/com/project/egloo/recipe/repository/RecipeRepository.java
  back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
Labels: backend, configuration, 레시피, 재료

#74 (#71) swagger configuration
  back-end-api/build.gradle
  back-end-api/src/main/java/com/project/egloo/common/config/SwaggerConfig.java
  back-end-api/src/main/java/com/project/egloo/common/config/WebConfig.java
Labels: backend, configuration

#78 (#77) 복합키 추가에 의한 ERD 수정
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/Ingredient.java
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/IngredientIDClass.java
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/IngredientRecipeIdClass.java
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/IngredientRecipeMapping.java
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/RecipeOption.java
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/UserIngredient.java
  back-end-api/src/main/java/com/project/egloo/ingredient/repository/IngredientRecipeMappingRepository.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Recipe.java
Labels: backend, configuration, 레시피, 재료

#80 (#79) redis configuration
  back-end-api/build.gradle
  back-end-api/src/main/java/com/project/egloo/EglooApplication.java
  back-end-api/src/main/java/com/project/egloo/common/config/AppConfig.java
  back-end-api/src/main/java/com/project/egloo/common/config/CacheConfig.java
  back-end-api/src/main/java/com/project/egloo/common/config/RedisConfig.java
  back-end-api/src/main/java/com/project/egloo/common/util/RedisUtil.java
Labels: enhancement, backend, configuration, 멤버

#83 (#77) ERD 구조 재변경 레시피/재료 중간에 조리과정 엔티티 추가
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/Ingredient.java
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/IngredientIDClass.java
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/RecipeOption.java
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/UserIngredient.java
  back-end-api/src/main/java/com/project/egloo/ingredient/repository/IngredientRepository.java
  back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Cooking.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Recipe.java
  back-end-api/src/main/java/com/project/egloo/recipe/repository/CategoryRepository.java
  back-end-api/src/main/java/com/project/egloo/recipe/repository/CookingRepository.java
  back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
Labels: backend, configuration, 레시피, 재료

#84 (#65) Features/FE/daum maps
  front-end/components/GeneralInput.vue
  front-end/components/RegisterModal.vue
  front-end/services/daumMaps.js
Labels: frontend

#86 (#85) 응답메시지 포멧 변경
  back-end-api/src/main/java/com/project/egloo/common/ResponseEntityObject.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/ErrorCode.java
  back-end-api/src/main/java/com/project/egloo/member/controller/MemberController.java
  back-end-api/src/main/java/com/project/egloo/member/service/MemberService.java
Labels: backend, configuration

#92 (#90) change Gradle DSL from groovy to kotlin
  back-end-api/build.gradle
  back-end-api/build.gradle.kts
  back-end-api/settings.gradle
  back-end-api/settings.gradle.kts
Labels: backend, configuration

#89 (#52) jwt token configuration and refactor login
  back-end-api/src/main/java/com/project/egloo/config/cors/CorsConfig.java
  back-end-api/src/main/java/com/project/egloo/config/jwt/JwtAccessDeniedHandler.java
  back-end-api/src/main/java/com/project/egloo/config/jwt/JwtAuthenticationEntryPoint.java
  back-end-api/src/main/java/com/project/egloo/config/jwt/JwtFilter.java
  back-end-api/src/main/java/com/project/egloo/config/jwt/JwtSecurityConfig.java
  back-end-api/src/main/java/com/project/egloo/config/jwt/TokenProvider.java
  back-end-api/src/main/java/com/project/egloo/config/security/AppProperties.java
  back-end-api/src/main/java/com/project/egloo/config/security/SecurityConfig.java
  back-end-api/src/main/java/com/project/egloo/member/controller/AuthController.java
  back-end-api/src/main/java/com/project/egloo/member/controller/MemberController.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Member.java
  back-end-api/src/main/java/com/project/egloo/member/dto/request/LoginRequest.java
  back-end-api/src/main/java/com/project/egloo/member/dto/response/TokenResponse.java
Labels: enhancement, backend, 멤버

#87 (#31) ERD 변경으로 인한 검색기능 수정
  back-end-api/src/main/java/com/project/egloo/common/StatusCode.java
  back-end-api/src/main/java/com/project/egloo/ingredient/repository/IngredientRepository.java
  back-end-api/src/main/java/com/project/egloo/member/service/MemberService.java
  back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
  back-end-api/src/main/java/com/project/egloo/recipe/repository/CookingRepository.java
  back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
Labels: backend, 레시피

#93 (#76) Chore/fe/register validation
  front-end/assets/css/common.css
  front-end/assets/css/transition.css
  front-end/components/GeneralInput.vue
  front-end/components/RegisterModal.vue
  front-end/components/SwitchTabInput.vue
  front-end/jest.config.js
  front-end/package.json
  front-end/pages/login.vue
  front-end/plugins/axios.js
  front-end/plugins/batchimEnding.js
  front-end/plugins/vee-validate.js
  front-end/plugins/vs-modal.js
  front-end/store/actions.js
  front-end/test/Components.spec.js
Labels: frontend, 멤버

#98 (#53) SpringSecurity enhancement by member
  back-end-api/src/main/java/com/project/egloo/common/AuthMember.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/ErrorCode.java
  back-end-api/src/main/java/com/project/egloo/config/security/UserPrincipal.java
  back-end-api/src/main/java/com/project/egloo/member/controller/AuthController.java
  back-end-api/src/main/java/com/project/egloo/member/controller/MemberController.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Member.java
  back-end-api/src/main/java/com/project/egloo/member/dto/request/SignUpRequest.java
  back-end-api/src/main/java/com/project/egloo/member/dto/response/SignUpResponse.java
  back-end-api/src/main/java/com/project/egloo/member/dto/response/TokenResponse.java
  back-end-api/src/main/java/com/project/egloo/member/repository/MemberRepository.java
  back-end-api/src/main/java/com/project/egloo/member/service/MemberService.java
Labels: backend, 멤버

#115 (#99) Ingredient configuration and delete redis
  back-end-api/src/main/java/com/project/egloo/common/config/RedisConfig.java
  back-end-api/src/main/java/com/project/egloo/ingredient/controller/IngredientController.java
  back-end-api/src/main/java/com/project/egloo/ingredient/service/IngredientService.java
Labels: backend, 재료

#117 (#116) fix: token provider @Value works correctly now, formatting code, unit test for creating token
  back-end-api/src/main/java/com/project/egloo/config/jwt/TokenProvider.java
  back-end-api/src/test/java/com/project/egloo/config/jwt/TokenProviderTest.java
Labels: enhancement, backend

#109 (#104) Feature/Fe/User profile Page
  front-end/assets/data/db.js
  front-end/pages/profile.vue
  front-end/store/profile/actions.js
  front-end/store/profile/getters.js
  front-end/store/profile/index.js
  front-end/store/profile/mutations.js
Labels: frontend
