Repository penguinsAtEgloo/E-Gloo, pull requests merged in 2021-09, with the labels that each got.

#121 (#114) 레시피 양방향 연관관계 설정, 코드 포맷팅, 변수명 조정
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/Ingredient.java
  back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Category.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Cooking.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Recipe.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/RecipeProcess.java
  back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
Labels: enhancement, backend, 재료

#122 (#119)레시피 메인 페이지 개발
  front-end/assets/data/db.js
  front-end/components/RecipesGrid.vue
  front-end/nuxt.config.js
  front-end/package.json
  front-end/pages/recipes.vue
  front-end/store/index.js
  front-end/store/recipes/actions.js
  front-end/store/recipes/getters.js
  front-end/store/recipes/index.js
  front-end/store/recipes/mutations.js
Labels: frontend, 레시피

#123 (#110) create recipe service, controller
  back-end-api/src/main/java/com/project/egloo/config/security/SecurityConfig.java
  back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Category.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Cooking.java
  back-end-api/src/main/java/com/project/egloo/recipe/domain/Recipe.java
  back-end-api/src/main/java/com/project/egloo/recipe/dto/BasicCategoryDTO.java
  back-end-api/src/main/java/com/project/egloo/recipe/dto/CreateRecipeDTO.java
  back-end-api/src/main/java/com/project/egloo/recipe/dto/RecipeDTO.java
  back-end-api/src/main/java/com/project/egloo/recipe/exception/CategoryNotFoundException.java
  back-end-api/src/main/java/com/project/egloo/recipe/repository/CategoryRepository.java
  back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
  back-end-api/src/test/java/com/project/egloo/recipe/controller/RecipeControllerTest.java
  back-end-api/src/test/java/com/project/egloo/recipe/service/RecipeServiceTest.java
Labels: enhancement, backend

#126 (#120) 재료 등록 페이지 개발
  front-end/assets/data/db.js
  front-end/assets/images/white.jpg
  front-end/components/IngredientsGrid.vue
  front-end/pages/ingredients.vue
  front-end/store/ingredients/actions.js
  front-end/store/ingredients/getters.js
  front-end/store/ingredients/index.js
  front-end/store/ingredients/mutations.js
Labels: frontend, 재료

#118 (#105) kakao naver 로그인 기능 추가
  back-end-api/.gitignore
  back-end-api/build.gradle.kts
  back-end-api/src/main/java/com/project/egloo/config/security/SecurityConfig.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Member.java
  back-end-api/src/main/java/com/project/egloo/member/domain/MemberRole.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Social.java
  back-end-api/src/main/java/com/project/egloo/member/service/CustomOAuth2UserService.java
  back-end-api/src/main/java/com/project/egloo/member/service/OAuth2Attribute.java
Labels: backend, 멤버

#129 (#128) login fixed(username -> email), password tpye fixed (varchar255)
  back-end-api/src/main/java/com/project/egloo/member/controller/AuthController.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Member.java
  back-end-api/src/main/java/com/project/egloo/member/dto/request/LoginRequest.java
  back-end-api/src/main/java/com/project/egloo/member/service/CustomMemberDetailsService.java
Labels: bug

#137 (#136) reformat java codes
  back-end-api/src/main/java/com/project/egloo/EglooApplication.java
  back-end-api/src/main/java/com/project/egloo/common/config/CacheConfig.java
  back-end-api/src/main/java/com/project/egloo/common/config/SwaggerConfig.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/AuthException.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/EntityNotFoundException.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/ErrorCode.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/ErrorResponse.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/GlobalExceptionHandler.java
  back-end-api/src/main/java/com/project/egloo/common/exceptions/InvalidValueException.java
  back-end-api/src/main/java/com/project/egloo/common/util/RedisUtil.java
  back-end-api/src/main/java/com/project/egloo/config/jwt/JwtFilter.java
  back-end-api/src/main/java/com/project/egloo/config/security/SecurityConfig.java
  back-end-api/src/main/java/com/project/egloo/config/security/UserPrincipal.java
  back-end-api/src/main/java/com/project/egloo/ingredient/controller/IngredientController.java
  back-end-api/src/main/java/com/project/egloo/ingredient/domain/Ingredient.java
  back-end-api/src/main/java/com/project/egloo/ingredient/service/IngredientService.java
  back-end-api/src/main/java/com/project/egloo/member/controller/AuthController.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Member.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Social.java
  back-end-api/src/main/java/com/project/egloo/member/dto/request/LoginRequest.java
  back-end-api/src/main/java/com/project/egloo/member/dto/response/SignUpResponse.java
  back-end-api/src/main/java/com/project/egloo/member/repository/MemberRepository.java
  back-end-api/src/main/java/com/project/egloo/member/service/MemberService.java
  back-end-api/src/main/java/com/project/egloo/member/service/OAuth2Attribute.java
Labels: backend

#139 feat: (#112) delete recipe API
  back-end-api/src/main/java/com/project/egloo/config/security/SecurityConfig.java
  back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
  back-end-api/src/main/java/com/project/egloo/recipe/dto/DeleteResultDTO.java
  back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
  back-end-api/src/test/java/com/project/egloo/recipe/service/RecipeServiceTest.java
Labels: backend, 레시피

#143 feat: (#111) update recipe API
  back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
  back-end-api/src/main/java/com/project/egloo/recipe/dto/PatchRecipeDTO.java
  back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
  back-end-api/src/test/java/com/project/egloo/recipe/service/RecipeServiceTest.java
Labels: backend, 레시피

#144 refac: (#113) refactor get recipe by ingredients API
  back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
Labels: backend, 레시피

#152 feat: (#151) update swagger, spring boot
  back-end-api/build.gradle.kts
  back-end-api/src/main/java/com/project/egloo/common/config/SwaggerConfig.java
  back-end-api/src/main/java/com/project/egloo/config/security/SecurityConfig.java
Labels: backend, configuration

#150 (#103) feature health check for server and config security
  back-end-api/build.gradle.kts
  back-end-api/src/main/java/com/project/egloo/config/security/SecurityConfig.java
  back-end-api/src/main/java/com/project/egloo/healthCheck/dto/HealthCheckDTO.java
  back-end-api/src/main/java/com/project/egloo/healthCheck/healthCheckController.java
  back-end-api/src/test/java/com/project/egloo/config/jwt/TokenProviderTest.java
Labels: CI/CD

#149 (#148) Mypage target member information find function
  back-end-api/.gitignore
  back-end-api/src/main/java/com/project/egloo/member/controller/AuthController.java
  back-end-api/src/main/java/com/project/egloo/member/dto/response/UserProfileResponse.java
  back-end-api/src/main/java/com/project/egloo/member/repository/MemberRepository.java
  back-end-api/src/main/java/com/project/egloo/member/service/MemberService.java
Labels: backend, 멤버

#156 fix: (#154) apply code review and resolve UserProfile commit
  back-end-api/build.gradle.kts
  back-end-api/src/main/java/com/project/egloo/config/security/SecurityConfig.java
  back-end-api/src/main/java/com/project/egloo/config/security/UserPrincipal.java
  back-end-api/src/main/java/com/project/egloo/member/controller/MemberController.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Member.java
  back-end-api/src/main/java/com/project/egloo/member/domain/MemberRole.java
  back-end-api/src/main/java/com/project/egloo/member/dto/request/SignUpRequest.java
  back-end-api/src/main/java/com/project/egloo/member/dto/response/MemberDTO.java
  back-end-api/src/main/java/com/project/egloo/member/dto/response/SignUpResponse.java
  back-end-api/src/main/java/com/project/egloo/member/mapper/MemberMapper.java
  back-end-api/src/main/java/com/project/egloo/member/service/CustomOAuth2UserService.java
  back-end-api/src/main/java/com/project/egloo/member/service/MemberService.java
  back-end-api/src/test/java/com/project/egloo/member/service/MemberServiceTest.java
Labels: backend, 멤버

#158 (#157) github action for elastic beanstalk
  back-end-api/.github/.workflows/benstalk.yaml
Labels: backend

#159 (#157) refactor github action for elastic beanstalkgit
  back-end-api/.github/.workflows/benstalk.yaml
Labels: CI/CD

#160 (#157) move github action for elastic beanstalk file
  .github/.workflows/benstalk.yaml
Labels: CI/CD

#161 (#157) edit github action for elastic beanstalk file
  .github/.workflows/benstalk.yml
Labels: CI/CD

#162 (#157) change package for gitAction
  .github/workflows/benstalk.yml
Labels: CI/CD

#163 (#157) change slack token webhook secret name
  .github/workflows/benstalk.yml
Labels: CI/CD
