Repository penguinsAtEgloo/E-Gloo, pull requests merged in 2021-10, with the labels that each got.

#164 fix: update working directory and change slack bot token secrets
  .github/workflows/benstalk.yml
Labels: backend, CI/CD

#165 fix: (#157) change build file (.jar) path
  .github/workflows/benstalk.yml
Labels: backend, CI/CD

#166 fix: (#157) update artifact path as well
  .github/workflows/benstalk.yml
Labels: backend, CI/CD

#168 (#167) member info method fixed
  back-end-api/src/main/java/com/project/egloo/config/jwt/TokenProvider.java
  back-end-api/src/main/java/com/project/egloo/config/security/UserPrincipal.java
  back-end-api/src/main/java/com/project/egloo/member/controller/AuthController.java
  back-end-api/src/main/java/com/project/egloo/member/domain/Member.java
  back-end-api/src/main/java/com/project/egloo/member/service/CustomMemberDetailsService.java
Labels: bug, backend

#169 (#153) 스토리 작성 페이지 개발
  front-end/pages/story/insert.vue
  front-end/store/story/insert/actions.js
  front-end/store/story/insert/getters.js
  front-end/store/story/insert/index.js
  front-end/store/story/insert/mutations.js
Labels: frontend
